### ISSUE TITLE
Kcl should handle :error return from Curve25519.derive_shared_secret called with bad arguments.

### ISSUE THREAD

**Issue by marcinkoziej** [mwmiller/kcl#1]
if box receives an empty public key, the calls:
`Kcl.State.new_peer -> Kcl.shared_secret` will pass an `:error` value to `Kcl.first_level_key` which will not match any function (because of byte_size guard).
Kcl should handle `:error` value returned from `Curve25519.derive_shared_secret`

**Comment by mwmiller** [comment]
Sorry so slow to respond.  I will make this update in an upcoming release.
